optimizer:
  n_wheels: 32
  n_max_iterations: 2000
  mutation_probability: 0.5
  mutation_rate: 0.05
env: 
  gravity: 
    x: 0.0                           # [m / s^2]
    y: -9.81                         # [m / s^2]
  inclined_plane:
    inclination: 20
    x_0: -30.0
    y_0: 3.0
    x_1: 30.0
    y_1: 0.0
  wheel:
    diam: 2.0
    density: 1.0
    friction: 2.0
    init_position: 
      x: -28.0                       # [m]
      y: 7.0                      # [m]
    init_linear_velocity: 
      x: 0.0                       # [m / s]
      y: -10.0                     # [m / s]
    init_angular_velocity: 0.0            # [rad / s]
    init_angle: 0.0                   # deg 
    noise: 
      position: 
        x: 0.0                       # Standard deviation [m]
        y: 0.0                       # Standard deviation [m]
      linear_velocity: 
        x: 0.0                        # Standard deviation [m / s]
        y: 0.0                        # Standard deviation [m / s]
      angular_velocity: 0.0             # Standard deviation [rad / s]
      angle: 0.0                      # Standard deviation [deg]