seed: 0
optimizer:
  n_wheels: 32
  n_max_iterations: 1000
  mutation_probability: 0.2
  mutation_rate: 0.04
env: 
  gravity: 
    x: 0.0
    y: -9.81
  inclined_plane:
    inclination: 20
    x_0: -30.0
    y_0: 3.0
    x_1: 30.0
    y_1: 0.0
  wheel:
    diam: 4.0
    density: 1.0
    friction: 2.0
    init_position: 
      x: -26.0
      y: 6.0
    init_linear_velocity:
      x: 0.0
      y: -10.0
    init_angular_velocity: 0.0
    init_angle: 0.0