optimizer:
  n_wheels: 4
  n_iterations: 100
  mutation_probability: 0.1
  mutation_rate: 0.1
env: 
  gravity: 
    x: 0.0                           # [m / s^2]
    y: -9.81                         # [m / s^2]
  inclined_plane:
    inclination: 20
    x_0: -10.0
    y_0: 5.0
    x_1: 10.0
    y_1: 0.0
  wheel:
    diam: 2.0
    density: 1.0
    friction: 1.0
    init_position: 
      x: -9.0                       # [m]
      y: 10.0                      # [m]
    init_linear_velocity: 
      x: 0.0                       # [m / s]
      y: -10.0                     # [m / s]
    init_angular_velocity: 0.0            # [rad / s]
    init_angle: 0.0                   # deg 
    noise: 
      position: 
        x: 0.10                       # Standard deviation [m]
        y: 0.10                       # Standard deviation [m]
      linear_velocity: 
        x: 0.0                        # Standard deviation [m / s]
        y: 0.0                        # Standard deviation [m / s]
      angular_velocity: 0.0             # Standard deviation [rad / s]
      angle: 0.0                      # Standard deviation [deg]